# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Package Drifty

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "Website/**"
      - "*.md"
      - "*.txt"
      - "qodana.yaml"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "Website/**"      
      - "*.md"
      - "*.txt"
      - "qodana.yaml"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  package-Drifty:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install required build dependencies for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libfreetype6-dev
        sudo apt-get install libgl-dev libglib2.0-dev libgtk-3-dev libpango1.0-dev libx11-dev libxtst-dev zlib1g-dev
    - name: Set up GraalVM JDK 20.0.1
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '20.0.1'
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        set-java-home: true
        native-image-job-reports: 'true'
        cache: 'maven'
        native-image-pr-reports: true
        components: 'native-image'
    - name: Package Drifty CLI for ${{ matrix.os }} with GraalVM
      run: mvn -Pbuild-drifty-cli-for-${{ matrix.os }} package
    - name: Set Up Maven version 3.8.8 # For GUI build issues, maven version 3.8.8 needs to be used
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.8
    - name: Build platform-specific C object for missing jdk libraries
      run: gcc -c config/missing_symbols.c -o config/missing_symbols-${{ matrix.os }}.o
    - name: Package Drifty GUI for ${{ matrix.os }} with GluonFX maven plugin
      run: mvn -Pbuild-drifty-gui-for-${{ matrix.os }} gluonfx:build gluonfx:package
    - name: Categorise build artifacts
      run: |
        mkdir CLI
        mkdir GUI        
        if [ ${{ matrix.os }} == "windows-latest" ]; then
          mv "target/CLI/windows/Drifty CLI.exe" -t CLI
          mv target/gluonfx/x86_64-windows/Drifty-1.0.msi "target/gluonfx/x86_64-windows/Drifty GUI.msi"
          mv target/gluonfx/x86_64-windows/Drifty.exe "target/gluonfx/x86_64-windows/Drifty GUI.exe"
          mv "target/gluonfx/x86_64-windows/Drifty GUI.msi" "target/gluonfx/x86_64-windows/Drifty GUI.exe" -t GUI
        elif [ ${{ matrix.os }} == "macos-latest" ]; then
          mv "target/CLI/macos/Drifty CLI" -t CLI
          mv target/gluonfx/x86_64-darwin/Drifty-1.0.pkg "target/gluonfx/x86_64-darwin/Drifty GUI.pkg"
          mv target/gluonfx/x86_64-darwin/Drifty.app "target/gluonfx/x86_64-darwin/Drifty GUI.app"
          mv "target/gluonfx/x86_64-darwin/Drifty GUI.pkg" "target/gluonfx/x86_64-darwin/Drifty GUI.app" -t GUI
        elif [ ${{ matrix.os }} == "ubuntu-latest" ]; then
          mv "target/CLI/linux/Drifty CLI" -t CLI
          mv target/gluonfx/x86_64-linux/Drifty "target/gluonfx/x86_64-linux/Drifty GUI"
          mv "target/gluonfx/x86_64-linux/Drifty GUI" -t GUI
        fi
    - name: Tar build files # To prevent file permission loss
      run: tar -cvf ${{ matrix.os }}.tar CLI GUI
    - name: Push generated artifacts for ${{ matrix.os }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-Build-Files
        path: ${{ matrix.os }}.tar
        
  generate-metadata-for-Drifty-artifacts:
    runs-on: ubuntu-latest
    needs: package-Drifty
    steps:
    - uses: actions/checkout@v3
    - name: Get Drifty version from version.json file
      run: |
        echo "VERSION=$(jq .version version.json | sed -r 's/"//g')" >> $GITHUB_ENV
        echo "### Drifty v$VERSION Built! :rocket:" >> $GITHUB_STEP_SUMMARY
    - name: Set Drifty version in pom.xml
      run: mvn versions:set -DnewVersion=$VERSION
    - name: Download Build artifacts
      uses: actions/download-artifact@v3
    - name: Make OS specific build directories
      run: |
        mkdir linux
        mkdir macos
        mkdir windows
    - name: Extract build files from tar
      run: |
        tar -xvf ubuntu-latest-Build-Files/ubuntu-latest.tar -C linux
        tar -xvf macos-latest-Build-Files/macos-latest.tar -C macos
        tar -xvf windows-latest-Build-Files/windows-latest.tar -C windows
    - name: List all build artifacts for Ubuntu
      run: tree linux
    - name: List all build artifacts for macOS
      run: tree macos
    - name: List all build artifacts for Windows
      run: tree windows
    # - name: Create Release ($VERSION) with automated release notes
      # run: gh release create v$VERSION --generate-notes '/path/to/asset.extension#Asset-Display-string' # Assets path to be added later
